ancestryapp/urls.py
from django.conf.urls import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from ancestryapp import views

# Create your tests here.

urlpatterns = patterns('',
    (r'^ancestry/$', 'ancestryapp.views.view',
    )
)

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
"""
urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_URL, 'show_indexes': True}),
    )
"""

demoapp/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('demoapp.views',
                       url(r'^demo/$', 'demo', name='demo'),
                       url(r'^delete_f/$', 'delete_upload', name='delete_f'),
                       )

genomelens/urls.py
from django.conf.urls import *
from django.contrib import admin
from genomelens import views
from genomelens.views import RegistrationView
admin.autodiscover()   # may no longer need this with django 1.7

file = open('applications.txt')
apps = [url('^'+x.strip()+'/$', x.strip()+'.views.run') for x in file]

# TODO: remove obsolete comments.
urlpatterns = patterns('',

    url(r'^$', views.apphome, name='home'),
    url(r'^uploadfile', 'genomelens.views.uploadhome1', name='test'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^success/url/$', views.success),
    url(r'^search-form/$', views.search_form),
    url(r'^search/$', views.search),
    url(r'^contact-form/$', views.contact),
    url(r'^uploadView/$', views.uploadView, name='uploadFile'),
    url(r'^someview/$', views.some_view),
    url(r'^texthome/$', views.home_page),
    url(r'^csvhome/$', views.uploadhome),
    url(r'^statinfo/$', 'genomelens.views.stat_info'),
    url(r'^demoapp/', include('demoapp.urls')),
    #url(r'^login/', 'django.contrib.auth.views.login'),
    url(r'^login/', views.user_login),
    url(r'^logout/', views.user_logout),
    url(r'^register/$', views.register),
    #url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page' : '/login'}),
    url(r'^mainmenu/$', 'genomelens.views.mainmenu'),
    url(r'^support/$', views.support),
    url(r'^about/$', views.about),
    url(r'^resetps/$', views.resetps),

    #url(r'^app1/$', 'ancestryapp.views.ancestry_index'),
    ##url(r^geneview/$', 'GeneViewApp.urls'),
    (r'^geneview/', include('GeneViewApp.urls')),
    url(r'^vcfstats/$', 'vcfstats.views.run'),
    (r'^app1/', include('ancestryapp.urls')),   #   TODO: make this URL more appropriate.

    #url(r'^accounts/', include('registration.urls')),
    #url(r'^registration/', include('registration.backends.default.urls')),
    url(r'^download/', views.download),

    url(r'^gemini/', include('GeminiApp.urls')),
    url(r'^skeleton/', include('skeleton.urls')),
    *apps
)

ancestryapp/models.py
from django.db import models
from jsonfield import JSONField
from demoapp.models import Document

import json

class VcfFile(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class PopulationData(models.Model):
    #vcf = models.ForeignKey(VcfFile)
    vcf = models.ForeignKey(Document)
    identifier = models.CharField(max_length=100)
    populations = JSONField()
    #app_label = 'ancestryapp'

    def __str__(self):
        return "%s\n%s\n%s" % (self.vcf, self.identifier, json.dumps(json.loads(self.populations), indent=4))

ancestryapp/views.py
from django.shortcuts import redirect, render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from genomelens.forms import UploadFileForm, ContactForm, AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.template import Context, loader, RequestContext

from genomelens.tasks import ancestry
from ancestryapp.models import VcfFile
from demoapp.models import Document, AppState

from ancestry_app import determine_ancestry
#from ancestryapp.tasks import Ancestry
#from django.template.context_processors import csrf
import csv
import time
import xlrd


def home(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        File = request.FILES.get('File')
        context = {}
        if File.multiple_chunks():
            context["uploadError"] = "Uploaded file is too big (%.2f MB)."
        else:
            context["uploadedFile"] = File.read()
        return render_to_response('upload.html', context)
    else:
        form = UploadFileForm()
        return render_to_response('testform.html',
                                  {'form': form},
                                  context_instance=RequestContext(request))


def view(request):
    if request.method == 'POST':

        # grab the path and primary key from the request and look up
        # the VCF file from the db
        fname = request.POST['vcf_path']
        pk = request.POST['vcf_id']
        vcf = Document.objects.get(id=pk)

        # get the current app state and handle appropriately
        current_state = vcf.ancestry_state
        if current_state == AppState.VCF_PROCESSING:
            # app is currently running ignore request
            return HttpResponse(
                "You have already started app. It is currently running.")

        elif current_state == AppState.VCF_UNPROCESSED \
                or current_state == AppState.VCF_PROCESSING_ERROR:
            # app hasn't been run or there was an error in a previous run
            # Start App task and return
            vcf.ancestry_state = AppState.VCF_PROCESSING
            vcf.save()
            result = ancestry.delay(fname, pk)  # task will handle changing state
            return HttpResponse(
                "Ancestry application has been started. You will be notified when completed.")

        else:
            # App has already been run successfully render template
            return render_to_response('ancestryview.html',
                                      {'vcf': vcf},
                                      context_instance=RequestContext(request))

    else:   # should always receive a POST request just return
        return

ancestryapp/templates/ancestryview.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>Ancestry View</title>
    <script src="http://d3js.org/d3.v3.js"></script>
    <link rel="stylesheet" type="text/css"
      href="https://fonts.googleapis.com/css?family=Open+Sans:400,600">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    {% load staticfiles %}
    {% load ancestry_tags %}
    <link rel="stylesheet" type="text/css" href="{% static 'ancestryapp/sequences.css' %}" />
  </head>

  <body>
    <div id="main">
      <div id="sequence"></div>

      <!-- Sunburst -->
      <div id="chart">
        <div id="explanation" style="visibility: hidden;">
          <span id="percentage"></span><br/>
          similar to <span id="population"></span>
        </div>
      </div>

      <!-- show drop down menu for all individuals associated with a vcf file -->
      <div id="footer" class="row">
        <div class="col-xs-3">
            <select class="form-control" name="dropdown" id="dropdown" onchange="OnChange()">
              {% for pop in vcf.populationdata_set.all %}
              <option value='{% change vcf pop.identifier %}'>{{ pop.identifier }}</option>
              {% endfor %}
            </select>
        </div>
      </div>

    </div>

    <!-- checkbox for showing the legend -->
    <div id="sidebar">
      <div id="description"></div>
      <div id="percents"></div>
      <input type="checkbox" id="togglelegend"> Legend<br/>
      <div id="legend" style="visibility: hidden;"></div>
    </div>

    <!-- inline javascript to grab initial value to render template -->
    <script type="text/javascript">
        var initial = '{% initial vcf %}';
    </script>

    <!-- Load sequences.js to draw sunburst -->
    <script type="text/javascript" src="{% static 'ancestryapp/sequences.js' %}"></script>
  </body>

</html>

ancestryapp/templates/index.html
<!doctype html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<title>Ancestry</title>
<body>
    <div class="container">
        <div class="jumbotron">
            <h2>Ancestry</h2>
            <form role="form" method="post" action="/">
                <div class="form-group">
                    <label for="vcf-file">VCF file</label>
                    <input type="file" id="vcf-file">
                    <p class="help-block">Path to VCF file for ancestry analysis</p>
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
    </div>
</body>
</html>