demoapp/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('demoapp.views',
                       url(r'^demo/$', 'demo', name='demo'),
                       url(r'^delete_f/$', 'delete_upload', name='delete_f'),
                       )

genomelens/urls.py
from django.conf.urls import *
from django.contrib import admin
from genomelens import views
from genomelens.views import RegistrationView
admin.autodiscover()   # may no longer need this with django 1.7

file = open('applications.txt')
apps = [url('^'+x.strip()+'/$', x.strip()+'.views.run') for x in file]

# TODO: remove obsolete comments.
urlpatterns = patterns('',

    url(r'^$', views.apphome, name='home'),
    url(r'^uploadfile', 'genomelens.views.uploadhome1', name='test'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^success/url/$', views.success),
    url(r'^search-form/$', views.search_form),
    url(r'^search/$', views.search),
    url(r'^contact-form/$', views.contact),
    url(r'^uploadView/$', views.uploadView, name='uploadFile'),
    url(r'^someview/$', views.some_view),
    url(r'^texthome/$', views.home_page),
    url(r'^csvhome/$', views.uploadhome),
    url(r'^statinfo/$', 'genomelens.views.stat_info'),
    url(r'^demoapp/', include('demoapp.urls')),
    #url(r'^login/', 'django.contrib.auth.views.login'),
    url(r'^login/', views.user_login),
    url(r'^logout/', views.user_logout),
    url(r'^register/$', views.register),
    #url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page' : '/login'}),
    url(r'^mainmenu/$', 'genomelens.views.mainmenu'),
    url(r'^support/$', views.support),
    url(r'^about/$', views.about),
    url(r'^resetps/$', views.resetps),

    #url(r'^app1/$', 'ancestryapp.views.ancestry_index'),
    ##url(r^geneview/$', 'GeneViewApp.urls'),
    (r'^geneview/', include('GeneViewApp.urls')),
    url(r'^vcfstats/$', 'vcfstats.views.run'),
    (r'^app1/', include('ancestryapp.urls')),   #   TODO: make this URL more appropriate.

    #url(r'^accounts/', include('registration.urls')),
    #url(r'^registration/', include('registration.backends.default.urls')),
    url(r'^download/', views.download),

    url(r'^gemini/', include('GeminiApp.urls')),
    url(r'^skeleton/', include('skeleton.urls')),
    *apps
)

genomelens/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    #website = models.URLField(blank=True)
    #picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

genomelens/forms.py
# In forms.py ....
from __future__ import unicode_literals
from collections import OrderedDict
from django import forms
from django.forms.utils import flatatt
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.html import format_html, format_html_join
from django.utils.http import urlsafe_base64_encode
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext, ugettext_lazy as _
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.hashers import UNUSABLE_PASSWORD_PREFIX, identify_hasher
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from genomelens.models import UserProfile
from django.contrib.auth.models import User
from django import forms

UNMASKED_DIGITS_TO_SHOW = 6

IMPORT_FILE_TYPES = ['.xls', ]

class UploadFileForm(forms.Form):
    # title = forms.CharField(max_length=50)
    File = forms.FileField()

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        #exclude = ('username.help_text') # this throws an error.

class UploadFileForm(forms.Form):
    # title = forms.CharField(max_length=50)
    File = forms.FileField()

class AuthenticationForm(forms.Form):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    username/password logins.
    """
    username = forms.CharField(max_length=254)
    password = forms.CharField(label=_("Password"), widget=forms.PasswordInput)

    error_messages = {
        'invalid_login': _("Please enter a correct %(username)s and password. "
                           "Note that both fields may be case-sensitive."),
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super(AuthenticationForm, self).__init__(*args, **kwargs)

        # Set the label for the "username" field.
        UserModel = get_user_model()
        self.username_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)
        if self.fields['username'].label is None:
            self.fields['username'].label = capfirst(self.username_field.verbose_name)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(username=username,
                                           password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.

        If the given user cannot log in, this method should raise a
        ``forms.ValidationError``.

        If the given user may log in, this method should return None.
        """
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache

class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }
    username = forms.RegexField(label=_("Username"), max_length=30,
        regex=r'^[\w.@+-]+$',
        help_text=_("Required. 30 characters or fewer. Letters, digits and "
                    "@/./+/-/_ only."),
        error_messages={
            'invalid': _("This value may contain only letters, numbers and "
                         "@/./+/-/_ characters.")})
    password1 = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_("Enter the same password as above, for verification."))

    class Meta:
        model = User
        fields = ("username",)

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(
            self.error_messages['duplicate_username'],
            code='duplicate_username',
        )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class ContactForm(forms.Form):
    subject = forms.CharField()
    email = forms.EmailField(required=False)
    message = forms.CharField()

class XlsInputForm(forms.Form):
    input_excel = forms.FileField(required = True, label = u"Upload the Excel file.")

    def clean_input_excel(self):
        input_excel = self.cleaned_data['input_excel']
        extension = os.path.splitext( input_excel.name)[1]
        if not (extension in IMPORT_FILE_TYPES):
            raise forms.ValidationError( u'%s is not a valid excel file.' %extension)
        else:
            return input_excel

genomelens/templates/about.html
<html>
	<head>
		<title>Genome length web application</title>
	</head>

	<body>
		<p> This page is still under construction ... </p>
	</body>
</html>

genomelens/templates/app1home.html
<html>
	<head>
		<title>Genome Lens Application</title>
	</head>
	<body>
		<div style = "padding: 0 0 0 0; width: 100%; margin: 1px;">
		<div>
		<nav style="text-align:center; padding: 3px; background: #dcdddc;">
			<ul>
				<li style="display: inline;"><a href="/">Home</a></li>
				<li style="display: inline;"><a href="/app1/">Application 1</a></li>
				<li style="display: inline;"><a href="/app2/">Application 2</a></li>
				<li style="display: inline;"><a href="/app3/">Application 3</a></li>
				<li style="display: inline;"><a href="/support/">Support</a></li>
				<li style="display: inline;"><a href="/logout/">Logout</a></li>
			</ul>
		</nav>
		</div>
		</div>

		<p> Application 1 </p>
	</body>
</html>

genomelens/templates/apphome-copy.html
{% load staticfiles %}
	<head>
		<title>Genome Lens Application</title>
		<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen" >
		<link href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet" media="screen" >
	</head>
	<style>
	body {
  padding-top: 30px;
  padding-bottom: 30px;
}

.theme-dropdown .dropdown-menu {
  position: static;
  display: block;
  margin-bottom: 20px;
}

.theme-showcase > p > .btn {
  margin: 5px 0;
}

.theme-showcase .navbar .container {
  width: auto;
}

/* Sticky footer styles
-------------------------------------------------- */
html {
  position: relative;
  min-height: 100%;
}
body {
  /* Margin bottom by footer height */
  margin-bottom: 60px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  /* Set the fixed height of the footer here */
  height: 60px;
  background-color: #f5f5f5;
}

.container .text-muted {
  margin: 20px 0;
}
	</style>

	<body>

		<div class="container theme-showcase" role="main">
			<div class="jumbotron">
	        	<h1>Genome Lens</h1>
			<h3>A Platform for Genomic Exploration</h3>
	        </div>

	    <div style="display: inline-block; width: 40%; padding-left: 20px; text-align: center;">
			<a class="btn btn-default btn-lg btn-block" href="/login/" role="Login">Log in</a>
			<br />
        	<p>Or</p>
			<a class="btn btn-default btn-lg btn-block" href="/register/" role="button">Sign up</a>
		</div>


		<div>
			<footer class="footer" role="contentinfo">
				<div style="display: inline-block; padding-left: 20%;">
					<p>About us</p>
					<p>Contact </p>
				</div>
				<div style="display: inline-block; padding-left: 20%;">
					<p>Support</p>
					<p>Get started</p>
				</div>
				<div style="display: inline-block; padding-left: 20%;">
					<p>Help center</p>
					<p>Privacy &amp terms</p>
				</div>
				<div style="text-align: center;">
					<p>CSE & Bioinformatics @ UCSD</p>
				</div>
			</footer>
		</div>

	</body>
</html>

genomelens/templates/apphome.html
{% load staticfiles %}
	<head>
		<title>Genome Lens Application</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width">
		<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen" >
		<link href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet" media="screen" >
		<link rel="stylesheet" href="{% static 'bootstrap/css/normalize.css'%}">
		<link rel="stylesheet" href="{% static 'bootstrap/css/style.css'%}">
		<link href='https://fonts.googleapis.com/css?family=Droid+Sans:700,400' rel='stylesheet' type='text/css'>
		
	</head>

	<body>
		<div id="content-container">
			<header id="main-header">
				<h1 class="main-logo">
					<a href="/"><img class="main-logo"  src="{% static 'GenomeLensLgtbluHeader.png' %}" alt="GenomeLens logo"></a>
				</h1>
				<ul class="user-buttons bold">
					<!-- <li><a href="demoapp/demo/#">{{ username }}</a> -->
					<li><a href="/login/">Sign in</a>
					<li><a href="/register/">Register</a>
				</ul>
				<ul class="main-nav bold">
					<li id="selected"><a href="/" >Home</a>
					<li ><a href="/support/">About</a>
					<li><a href="/support/">Research</a>
					<li><a href="/support/">Contact</a>
				</ul>
					
			</header>
			<div class="main-content">
				<img id="cover-logo" src="{% static 'GenomeLensDrkBlu.png' %}">
				<div class= "push"></div>

			</div>
		</div>
	   <!--  <div style="display: inline-block; width: 40%; padding-left: 20px; text-align: center;">
			<a class="btn btn-default btn-lg btn-block" href="/login/" role="Login">Log in</a>
			<br />
        	<p>Or</p>
			<a class="btn btn-default btn-lg btn-block" href="/register/" role="button">Sign up</a>
		</div> -->

		<footer class="main-footer">
		<div class="nav-container">
			<ul class="mainlower-nav">
				<li><a href="/" >Home</a>
				<li><a href="about.html">About</a>
			</ul>
			<ul class="mainlower-nav">	
				<li><a href="research.html">Research</a>
				<li><a href="contact.html">Contact</a>
			</ul>
			<ul class="mainlower-nav">
				<li><a href="Support.html">Support</a>
				<li><a href="GetStarted.html">GetStarted</a>
			</ul>
			<ul class="mainlower-nav pressfix">	
				<li class="pressfix"><a href="Help.html">Help Center</a>
				<li><a href="Terms.html">Privacy &<wbr> Terms</a>
			</ul>
		</div>
		
			<p>UCSD Bioinformatics &copy; 2015</p>
		</footer>

	</body>
</html>

genomelens/templates/apphome_old.html
<!DOCTYPE html>
<html>
	<head>
		<title>GenLens</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<link rel="stylesheet" href="/static/sitestyle.css" type="text/css" >
	</head>

	<body>

		<div class="top">
			<nav>
				<ul>
					<li><a class="tl" href="/about">GenLens Demo</a></li>
					<li style="padding-left: 80px"><img class="logo" src="/static/logo_pic.jpg"><span style="logo"><font color=#307BEA size="6">GenLens</font></span></li>
					<li style="padding-left: 80px"><a href="/register/">
						<input type="submit" class="styled-button-4" value="Register" /> </a></li>
					<li style="padding-left: 50px"><a class="styled-button-12" href="/login">Sign in</a></li>
				</ul>
			</nav>
		</div>

		<img class="backgrd1" src="/static/logo_pic.jpg" alt="Logo Image">


		<div class="s1"> 
			<h2 class="pos_right">
				GenLens 
				<br>
				<p style="word-wrap: break-word;">
					SOME DESCRIPTION HERE...
				</p>
				</h2>
		</div>

		{% extends "registration/base.html" %}
		{% block content %}

		<div class="s2">
		  {% if form.errors %}
		  <p class="errors">Please correct the errors below: {{ form.non_field_errors }}</p>
		  {% endif %}
		  
		  <form class="signinform" method="post" action="" class="wide">
			{% csrf_token %}
		    <p>
		      <label for="id_usrname">User Name:</label>
		      {{ form.username }}
		    </p>
		    <p>
		      <label for="id_email">Email Address:</label>
		      {% if form.email.errors %}
		        <p class="errors">{{ form.email.errors.as_text }}</p>
		      {% endif %}
		      {{ form.email }}
		    </p>
		    <p>
		      <label for="id_password1">Password:</label>
		      {% if form.password1.errors %}
		        <p class="errors">{{ form.password1.errors.as_text }}</p>
		      {% endif %}
		      {{ form.password1 }}
		    </p>
		    <p>
		      <label for="id_password2">Confirm Password:</label>
		      {% if form.password2.errors %}
		        <p class="errors">{{ form.password2.errors.as_text }}</p>
		      {% endif %}
		      {{ form.password2 }}
		    </p>

		    <input type="checkbox" name="agreement" value="yesno">I agree to GenLens terms<br>
		    <input class="lsubmitbar" type="submit" value="Register &rarr;" >

		  </form>

		  <img class="backgrd2" src="/static/can-stock-photo_csp11681668.jpg" alt="Logo Image";>
		</div>

		<div class="s3">
			<img class="backgrd3" src="/static/images-humangenomesequencing.jpg" alt="Logo Image";>
			<p>
				ANOTHER SECTION: IMAGE OR TEXT DESCRIPTION
				<br>
				PLACEHOLDER
			</p>
		</div>


		<div class="ip">
			<div>
			<footer class="footer" role="contentinfo">
				<div style="padding: 1rem; ">
					<div style="text-align: center;">Bioinformatics group at UCSD &amp; fine print</div>
				</div>
			</footer>
			</div>
		</div>
		{% endblock %}
	</body>
</html>

genomelens/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>GenomeLens</title>
</head>
<body>
<div style="margin: 0; padding: 0; width: 79%; position: relative; display:inline-block;">
<div style="float: left;">
<div id="sidebar">
    {% block sidebar %}
    <ul>
        <li><a href="/">Home</a></li>

        {% if user.is_authenticated %}
            <li><a href="/logout">Logout</a></li>
        {% else %}
            <li><a href="/login">Login</a></li>
        {% endif %}
    </ul>
    {% endblock %}
</div>

<div id="content">  
    {% block content %}
    {% endblock %}
</div>


</body>
</html>

genomelens/templates/demo.html
<html>
	<head>
		<title>Genome Lens Application Demonstration </title>
	</head>

	<body>
		<div style="padding-top: 10px;">
			<b>List of uploaded VCF files:</b>
		</div>

		{% if documents %}
			<ul>
			{% for document in documents %}
				<li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
			{% endfor %}
			</ul>
		{% else %}
			<p>No documents.</p>
		{% endif %}

		<!-- Upload form. Note enctype attribute! -->
        <form action="{%url "demo" %}" enctype="multipart/form-data" method="post" action=".">
            {% csrf_token %}
			<p>{{ form.non_field_errors }}</p>
			<p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
			<p>
				{{ form.docfile.errors }}
				{{ form.docfile }}
			</p>
			<p><input type="submit" value="Upload" /></p>
		</form>


        	<div style="padding-top: 10px;">
				<b>Available Applications</b>
			</div>

			<div style="padding-top: 10px;">
				<a href="/geneview/geneview/"> GenView App </a>
			</div>

			<div style="padding-top: 10px;">
				<a href="/app1/ancestry/"> Ancestry App </a>
			</div>

			<div style="padding-top: 10px;">
				<a href="/app3/"> VCFstats App </a>
			</div>
        


	</body>
</html>

genomelens/templates/download.html
<html>
	<head>
		<title>Genome length web application</title>
	</head>

	<body>
		<p> This page is still under construction ... </p>
	</body>
</html>

genomelens/templates/form.html
<html>
	<head>
    	<title>Input (VCF, 23andme, bedfiles, excel)</title>
	</head>
	<body>

		<fieldset>
		
		<div style="padding: 0 0 0 0; width: 100%; margin: 1px;">
		<div>
		<nav style="text-align:center; padding: 3px; background: #dcdddc;">
			<ul>
				<li style="display: inline;"><a href="/">Home</a></li>
				<li style="display: inline;"><a href="/app1/">Application 1</a></li>
				<li style="display: inline;"><a href="/app2/">Application 2</a></li>
				<li style="display: inline;"><a href="/app3/">Application 3</a></li>
				<li style="display: inline;"><a href="/support/">Support</a></li>
				<li style="display: inline;"><a href="/logout/">Logout</a></li>
			</ul>
		</nav>
		</div>
		</div>

		<h1 class="centered">Input (VCF, 23andme, bedfiles, excel)</h1>
		
		<form method="post" action="http://localhost:8000/uploadView/"
		{% if form.is_multipart %}
			enctype="multipart/form-data"
		{% endif %}>
		{% csrf_token %}
		{{form}}
		<input type="submit" value="Submit" name="submit">
		</form>

	</body>
</html>

genomelens/templates/login.html
{% load staticfiles %}
    <head>
        <title>Genome Lens Application Demonstration </title>
 		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width">
		<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen" >
		<link href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet" media="screen" >
		<link rel="stylesheet" href="{% static 'bootstrap/css/normalize.css'%}">
		<link rel="stylesheet" href="{% static 'bootstrap/css/style.css'%}">
		<link rel="stylesheet" href="{% static 'bootstrap/css/form.css'%}">
		<link href='https://fonts.googleapis.com/css?family=Droid+Sans:700,400' rel='stylesheet' type='text/css'>
		
	</head>

    <body>
		<div id="content-container">
			<header id="main-header">
				<h1 class="main-logo">
					<a href="/"><img class="main-logo"  src="{% static 'GenomeLensLgtbluHeader.png' %}" alt="GenomeLens logo"></a>
				</h1>
				<ul class="user-buttons bold">
					<li id="selected"><a href="/login/">Sign in</a>
					<li><a href="/register/">Register</a>
				</ul>
				<ul class="main-nav bold">
					<li ><a href="/" >Home</a>
					<li ><a href="/support/">About</a>
					<li><a href="/support/">Research</a>
					<li><a href="/support/">Contact</a>
				</ul>
					
			</header>

			<div class="main-content">
				<form method="post" action="." enctype="multipart/form-data">
					{% csrf_token %}
					<p style="font-weight: bold; display: inline-block;">Username:&nbsp</p><input type="text" name="username" value="" size="25" />
					<br />
					<p style="font-weight: bold; display: inline-block;">Password:&nbsp</p><input type="password" name="password" value="" size="25" />
					<br />

					<input type="submit" value="Log in" />
				</form>
			</div>
		</div>
		<footer class="main-footer">
		<div class="nav-container">
			<ul class="mainlower-nav">
				<li><a href="/" >Home</a>
				<li><a href="about.html">About</a>
			</ul>
			<ul class="mainlower-nav">	
				<li><a href="research.html">Research</a>
				<li><a href="contact.html">Contact</a>
			</ul>
			<ul class="mainlower-nav">
				<li><a href="Support.html">Support</a>
				<li><a href="GetStarted.html">GetStarted</a>
			</ul>
			<ul class="mainlower-nav pressfix">	
				<li class="pressfix"><a href="Help.html">Help Center</a>
				<li><a href="Terms.html">Privacy &<wbr> Terms</a>
			</ul>
		</div>
		
			<p>UCSD Bioinformatics &copy; 2015</p>
		</footer>
    </body>
</html>

genomelens/templates/mainmenu.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    <title>{% block title %}templates/mainmenu.html{% endblock %}</title>
</head>
<body>

<div id="content">
    {% block content %}
    Main Menu <br>
    <a href="/app1/">Application 1</a> <br>
    <a href="/app2/">Application 2</a> <br>
    <a href="/app3/">Application 3</a> <br>
    {% endblock %}

</div>

</body>
</html>

genomelens/templates/register.html
{% load staticfiles %}
    <head>
        <title>Genome Lens Application Demonstration </title>
 		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width">
		<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen" >
		<link href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet" media="screen" >
		<link rel="stylesheet" href="{% static 'bootstrap/css/normalize.css'%}">
		<link rel="stylesheet" href="{% static 'bootstrap/css/style.css'%}">
		<link rel="stylesheet" href="{% static 'bootstrap/css/form.css'%}">
		<link href='https://fonts.googleapis.com/css?family=Droid+Sans:700,400' rel='stylesheet' type='text/css'>	
	</head>


    <body>
		<div id="content-container">
			<header id="main-header">
				<h1 class="main-logo">
					<a href="/"><img class="main-logo"  src="{% static 'GenomeLensLgtbluHeader.png' %}" alt="GenomeLens logo"></a>
				</h1>
				<ul class="user-buttons bold">
					<li><a href="/login/">Sign in</a>
					<li id="selected"><a href="/register/">Register</a>
				</ul>
				<ul class="main-nav bold">
					<li ><a href="/" >Home</a>
					<li ><a href="/support/">About</a>
					<li><a href="/support/">Research</a>
					<li><a href="/support/">Contact</a>
				</ul>
					
			</header>
			<div class="main-content">
			{% if registered %}
			<div style="padding-top: 20px; padding-left: 20px; font-family:'Lucida Grande',Tahoma,Verdana,Arial,Sans-serif";>
				<strong>Thank you for registering!  </strong>
				<a href="/login/">You may log in here.</a><br />
			</div>
			{% else %}
		   
			<form style="padding-left: 20px;" id="user_form" method="post" action=""
					enctype="multipart/form-data">

				{% csrf_token %}

				{{ user_form.as_p }}

				<input type="checkbox" name="agreement" value="yesno"> I agree to <a href="/about/">Genome Lens terms</a><br>
				<input type="submit" name="submit" value="Sign up" />
			</form>
			{% endif %}
			</div>
		</div>
		<footer class="main-footer">
			<div class="nav-container">
				<ul class="mainlower-nav">
					<li><a href="/" >Home</a>
					<li><a href="about.html">About</a>
				</ul>
				<ul class="mainlower-nav">	
					<li><a href="research.html">Research</a>
					<li><a href="contact.html">Contact</a>
				</ul>
				<ul class="mainlower-nav">
					<li><a href="Support.html">Support</a>
					<li><a href="GetStarted.html">GetStarted</a>
				</ul>
				<ul class="mainlower-nav pressfix">	
					<li class="pressfix"><a href="Help.html">Help Center</a>
					<li><a href="Terms.html">Privacy &<wbr> Terms</a>
				</ul>
			</div>
		
			<p>UCSD Bioinformatics &copy; 2015</p>
		</footer>
    </body>
</html>

genomelens/templates/stat_info.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    <title>{% block title %}templates/mainmenu.html{% endblock %}</title>
</head>
<body>

<div id="content">
    {% block content %}
    Main Menu
    <a href="/statinfo/">Stat Info</a>
    {% endblock %}

</div>

</body>
</html>

genomelens/templates/testform.html
<html>
	<head>
    	<title>Input (VCF, 23andme, bedfiles, excel)</title>
	</head>
	<body>
		
		<fieldset>
		
		<div style="padding: 0 0 0 0; width: 100%; margin: 1px;">
		<div>
		<nav style="text-align:center; padding: 3px; background: #dcdddc;">
			<ul>
				<li style="display: inline;"><a href="/">Home</a></li>
				<li style="display: inline;"><a href="/app1/">Application 1</a></li>
				<li style="display: inline;"><a href="/app2/">Application 2</a></li>
				<li style="display: inline;"><a href="/app3/">Application 3</a></li>
				<li style="display: inline;"><a href="/support/">Support</a></li>
				<li style="display: inline;"><a href="/logout/">Logout</a></li>
			</ul>
		</nav>
		</div>
		</div>

		<h1 class="centered">Input (VCF, 23andme, bedfiles, excel)</h1>
		<form action="." method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<fieldset>
		    {{form}}
		    <input type="submit" value="Submit" name="submit">
			</fieldset>
			<p> &#9658 Acceptable formats </p>
		</form>
		</fieldset>
	</body>
</html>